### ISSUE TITLE
SMILExtract Release Executable does not run on Windows 10

### ISSUE THREAD

**Issue by sahanaamurthy** [naxingyu/opensmile#24]
I built Release+Win32 OpenSMlLE version using VS2017 on Windows 10(64bit OS). It was successful and it generated the files in msvcbuild. But when I try running the SMILExtract_Release executable, it doesn't do anything. When I tried SMILExtract -h on the command prompt, I get "SMILExtract' is not recognized as an internal or external command, operable program or batch file." Could someone please help me to verify if my build was successful and how to get this running on my system? Thanks!

**Comment by shiva12121** [comment]
you should use from this way opensmile-2.3.0\bin\Win32\SMILExtract_Release -h
but i dont know how use SMILExtract -c???
if who know it??

**Comment by atwing** [comment]
solved in #1

**Comment by atul56** [comment]
C:\Users\HP\Desktop\opensmile-3.0-win-x64>cd Desktop\opensmile-3.0-win-x64\bin\SMILExtract -h
The system cannot find the path specified.
 
I am getting this error. I think Iam not able to insatll properly 
plz guide, m using windows 10
