### ISSUE TITLE
Basic Command for running OpenSMILE not working

### ISSUE THREAD

**Issue by DiptarkBose** [naxingyu/opensmile#33]
I recently setup OpenSMILE on my Windows10 machine, and it does work fine when I run the initial SMILExtract_Release -h command.

But when I run the first basic command mentioned in the SMILE book (i.e, `SMILExtract_Release -C config/demo/demo1_energy.conf -I wav_samples/speech01.wav -O speech01.energy.csv`), I get the following error:

![image](https://user-images.githubusercontent.com/21203266/83484885-8975d400-a4c3-11ea-86fd-63c7238c7c34.png)

When I attempted to understand what could have raised the problem, I noticed that the folder doesn't have any wav_samples folder at all. So to fix this, I made my own wav_samples folder, and put a .wav file titled speech01.wav file inside it. Ran the command again, but still getting the same error.

Any help would be appreciated!

**Comment by naxingyu** [comment]
There is sample data in example-audio/opensmile.wav. Try using absolute path.

**Comment by DiptarkBose** [comment]
Understood. Thanks for the clarification @naxingyu !
